from youtube_transcript_api import (
    YouTubeTranscriptApi,
    TranscriptsDisabled,
    NoTranscriptFound,
    VideoUnavailable
)

from langchain_text_splitters import RecursiveCharacterTextSplitter


def extract_video_id(url):
    """
    Extract YouTube video ID from different URL formats.
    """

    if "v=" in url:
        return url.split("v=")[1].split("&")[0]

    elif "youtu.be/" in url:
        return url.split("youtu.be/")[1].split("?")[0]

    elif "shorts/" in url:
        return url.split("shorts/")[1].split("?")[0]

    return None


def get_video_transcript(url):

    print(f"\n--- Step 1: Fetching transcript ---")

    try:
        # Extract ID
        video_id = extract_video_id(url)

        if not video_id:
            raise ValueError("Invalid YouTube URL")

        print(f"Video ID: {video_id}")

        # Create API object
        api = YouTubeTranscriptApi()

        # Fetch transcript list
        transcript_list = api.list(video_id)

        transcript = None

        # Try manually created transcript first
        try:
            transcript = transcript_list.find_manually_created_transcript(['en'])
            print("Using manual English transcript")

        except:
            # Fallback to autogenerated
            transcript = transcript_list.find_generated_transcript(['en'])
            print("Using auto-generated English transcript")

        # Fetch transcript data
        fetched_transcript = transcript.fetch()

        # Combine text
        full_text = " ".join(
            [chunk.text for chunk in fetched_transcript]
        )

        print("✅ Transcript fetched successfully")
        return full_text

    except TranscriptsDisabled:
        print("❌ Transcripts are disabled for this video")

    except NoTranscriptFound:
        print("❌ No transcript found")

    except VideoUnavailable:
        print("❌ Video unavailable")

    except Exception as e:
        print(f"❌ Unexpected Error: {e}")

    return None


def split_text(text):

    print("\n--- Step 2: Chunking Text ---")

    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=1000,
        chunk_overlap=150,
        separators=["\n\n", "\n", ".", " ", ""]
    )

    chunks = text_splitter.split_text(text)

    print(f"✅ Created {len(chunks)} chunks")

    return chunks